### ISSUE TITLE
The @noninjectable decorator is silently order dependent

### ISSUE THREAD

**Issue by davidparsson** [alecthomas/injector#141] opened 2020-03-18 12:57 UTC
Passing (correct) example:

```
        class A:
            @injector.inject
            @injector.noninjectable('boolean')
            def __init__(self, boolean: bool = True) -> None:
                self.boolean = boolean

        i = injector.Injector()
        a = i.create_object(A)

        assert a.boolean is True
```

Failing example:
```
        class A:
            @injector.noninjectable('boolean')  # <-- @noninjectable before @inject
            @injector.inject
            def __init__(self, boolean: bool = True) -> None:
                self.boolean = boolean

        i = injector.Injector()
        a = i.create_object(A)

        assert a.boolean is True  # This will raise
```

This is dangerous, since it's an easy mistake to make and it's hard to discover.

**Comment by jstasiak** [comment] 2020-12-04 13:37
Please provide the Python and Injector versions you're running, I can't reproduce this.

**Comment by davidparsson** [comment] 2020-12-05 18:57
When this was reported I used Python 3.7.2 and Injector 0.15.0. so not the latest and greatest. I haven't verified that I could reproduce this again.

**Comment by jstasiak** [comment] 2020-12-05 19:09
I can reproduce this with 0.15.0 but it's fixed in 0.16.0 and later versions, I'll add a test to make sure we don't regress.

**Comment by davidparsson** [comment] 2020-12-05 19:20
Excellent! Thanks!

**Closed** 2020-12-06 12:59 UTC
