### ISSUE TITLE
Why singleton scope doesn't work as expected for create_child_injector 

### ISSUE THREAD

**Issue by panyi121** [alecthomas/injector#72] opened 2017-10-10 00:47 UTC
Hi, 

I have a use case to take in user inputs (name, description) at runtime at a top-level class, while some lower-level class also needs to depend on user inputs. 

While I tried with the below code, it throws Exception: Instantiation of <class 'injector.description'> prohibited - it is derived from BaseKey so most likely you should bind it to something.

But if I remove the @singleton annotation for class B, it works. Can someone explain to me why singleton scope doesn't work in the child_injector? 

```python
class base:
    def __init__(self, name):
        def configure(binder):
            binder.bind(Name, to=InstanceProvider(name))

        self.injector = Injector(configure)
        print('base: {}'.format(self.injector.get(Name)))


class A(base):
    def __init__(self, name, description):
        super(A, self).__init__(name)

        def configure(binder):
            binder.bind(Description, to=InstanceProvider(description))

        self.injector = self.injector.create_child_injector(configure)

        print(self.injector.get(B))


@singleton
class B:
    @inject(name=Name, description=Description)
    def __init__(self, name, description):
        self.name = name


A(name='hello', description='world')
```

===================================================================
Output:

```
base: hello
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/injector.py", line 580, in get
    return self._context[key]
KeyError: (<class '__main__.B'>,)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yipan/AlexaPrize-Python-Alexa-SDK/src/AlexaPrizeSocialbotCore/src/demo/di.py", line 191, in <module>
    A(name='hello', description='world')
  File "/Users/yipan/AlexaPrize-Python-Alexa-SDK/src/AlexaPrizeSocialbotCore/src/demo/di.py", line 180, in __init__
    print(self.injector.get(B))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/injector.py", line 743, in get
    result = scope_instance.get(key, binding.provider).get(self)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/injector.py", line 60, in wrapper
    return function(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/injector.py", line 582, in get
    provider = InstanceProvider(provider.get(self.injector))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/injector.py", line 144, in get
    return injector.create_object(self._cls)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/injector.py", line 787, in create_object
    init(instance, **additional_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/injector.py", line 1152, in inject
    kwargs=kwargs
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/injector.py", line 894, in call_with_injection
    owner_key=self_.__class__ if self_ is not None else callable.__module__,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/injector.py", line 60, in wrapper
    return function(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/injector.py", line 937, in args_to_inject
    instance = self.get(key.interface)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/injector.py", line 743, in get
    result = scope_instance.get(key, binding.provider).get(self)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/injector.py", line 144, in get
    return injector.create_object(self._cls)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/injector.py", line 787, in create_object
    init(instance, **additional_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/injector.py", line 1188, in __init__
    'so most likely you should bind it to something.' % (self.__class__,))
Exception: Instantiation of <class 'injector.description'> prohibited - it is derived from BaseKey so most likely you should bind it to something.

Process finished with exit code 1
```

**Comment by alecthomas** [comment] 2017-10-10 03:59
I think this is directly related to #52, though it wasn't clear at the time why that one was failing.

The problem is that `SingletonScope` is bound to the root `Injector`. The child injector looks up the `@singleton` binding, which resolves to the instance bound to the root injector.

This definitely should not be the case. Here's the equivalent code in Guice, which does what you would expect:

```java
Injector injector = Guice.createInjector(binder -> binder.bind(A.class));
Injector childa = injector.createChildInjector(binder -> binder.bind(B.class));
Injector childb = injector.createChildInjector(binder -> binder.bind(B.class));

assertThat(injector.getInstance(A.class)).isSameAs(injector.getInstance(A.class));
assertThat(childa.getInstance(A.class)).isSameAs(injector.getInstance(A.class));
assertThat(childa.getInstance(A.class)).isSameAs(childb.getInstance(A.class));
assertThat(childa.getInstance(B.class)).isNotSameAs(childb.getInstance(B.class));
assertThat(childa.getInstance(B.class)).isSameAs(childa.getInstance(B.class));
 ```

**Comment by jstasiak** [comment] 2017-10-16 15:05
This is fixed in https://github.com/alecthomas/injector/commit/de979a013be4cc3e9c6ae2ca667ce92c64213ca2 (not released yet).

**Closed by jstasiak** 2017-10-16 15:05 UTC
